Merger bin
membraneframework/membrane_video_merger_plugin pull request #4
Opened 2021-07-22 08:56 UTC by DominikWolek

2021-07-22 13:14 UTC, bblaszkow06 requested changes

2021-07-22 13:14 UTC, bblaszkow06 commented on lib/merger_bin.ex
> +              ]
Since this is pad-specific, it's a perfect fit for pad options - (https://hexdocs.pm/membrane_core/Membrane.Pad.html#t:common_spec_options_t/0) they are available via context (`ctx.pads[pad_ref]`) starting from `handle_pad_added`

2021-07-22 13:14 UTC, bblaszkow06 commented on lib/merger.ex
> +defmodule Membrane.VideoMerger.Merger do
Not a big fan of this change. What is the reason behind it? What's wrong with `Membrane.VideoMerger` and `Membrane.VideoMergerBin`?

2021-07-22 13:14 UTC, bblaszkow06 commented on lib/merger_bin.ex
> +defmodule Membrane.VideoMerger.MergerBin do
I'm wondering if we could be more semantic here. What do you think about `Membrane.VideoCutAndMerge`

2021-07-22 13:14 UTC, bblaszkow06 commented on lib/merger_bin.ex
> +      - `:offset` - Offset aplied to all franes' presentation timestamp values.
```suggestion
      - `:offset` - Offset applied to all frames' presentation timestamp values.
```

2021-07-22 13:14 UTC, bblaszkow06 commented on lib/merger_bin.ex
> +      List.foldl(streams, [], fn stream = %Stream{id: id}, elems ->
Why not `Enum.map/2`?

2021-07-22 13:14 UTC, bblaszkow06 commented on lib/merger_bin.ex
> +  defp cutter_id(id), do: String.to_atom("cutter_#{id}")
`String.to_atom` should be rather avoided. Why do you even enforce atoms? Anyway, using pad options should make this problem irrelevant.

2021-07-22 13:50 UTC, DominikWolek commented on lib/merger.ex
> +defmodule Membrane.VideoMerger.Merger do
Well, nothing is wrong with previous names: I just wanted to wanted all modules in this plugin to share unique common prefix.

2021-07-23 12:01 UTC, bblaszkow06 requested changes

2021-07-23 12:01 UTC, bblaszkow06 commented on lib/cut_and_merge.ex
> +        describtion: "List of streams to merge"
It's not a list anymore

2021-07-23 12:01 UTC, bblaszkow06 commented on test/cut_and_merge/cut_and_merge_test.exs
> +      end)
I get a feeling you're overusing `foldl` a bit:
1. Usually it's more common to use `Enum.reduce`
2. It's very generic and powerful - you can implement most of the functions in Enum using it - but I'd rather use it as a last resort
3. Here you don't really need to have elems and links at this stage 
4. Using an imperative counter like this in functional programming is a bit 'meh'

My suggestion (feel free to modify it and check if it's OK - it was written only here, on github without formatter nor compiler)
```suggestion
    elem_names =
      streams
      |> Enum.with_index(fn stream, i ->
         {stream, "file_src_#{i}", "parser_#{i}", "decoder_#{i}"}
      end)

    elems =
      elem_names
      |> Enum.flat_map(fn {_stream, src_i, parser_i, decoder_i} ->
        [
          {src_i,
           %File.Source{
             chunk_size: 40_960,
             location: "./test/fixtures/test_video_10s.h264"
           }},
          {parser_i, %H264.FFmpeg.Parser{framerate: @framerate}},
          {decoder_i, H264.FFmpeg.Decoder}
        ]
      end)

    links =
      elem_names
      |> Enum.map(fn {stream, src_i, parser_i, decoder_i} ->
          link(src_i)
          |> to(parser_i)
          |> to(decoder_i)
          |> via_in(Pad.ref(:input, i), options: [stream: stream])
          |> to(:merger_bin)
      end)
      
    elems = [merger_bin: CutAndMerge, sink: Testing.Sink | elems]
    links = [link(:merger_bin) |> to(:sink) | links]
```

2021-07-26 08:07 UTC, bblaszkow06 approved these changes

2021-07-26 11:22 UTC, merged